// **********************************************************************
//
// Copyright (c) 2003-2016 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.3
//
// <auto-generated>
//
// Generated from file `soporte.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package soporte;

public interface _ModeradorOperationsNC
{
    void addCliente(ClientePrx cliente);

    void removeCliente(ClientePrx cliente);

    void addOficinista(OficinistaPrx oficinista);

    void removeOficinista(OficinistaPrx oficinista);

    void responderCliente(OficinistaPrx oficinista, String mensaje);

    void responderOficinista(ClientePrx cliente, String mensaje);
}
