// **********************************************************************
//
// Copyright (c) 2003-2016 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.3
//
// <auto-generated>
//
// Generated from file `soporte.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package soporte;

public interface Cliente extends Ice.Object,
                                 _ClienteOperations, _ClienteOperationsNC
{
    public static final String ice_staticId = "::soporte::Cliente";

    public static final long serialVersionUID = -366765919L;
}
