// **********************************************************************
//
// Copyright (c) 2003-2016 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.3
//
// <auto-generated>
//
// Generated from file `soporte.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package soporte;

public interface ModeradorPrx extends Ice.ObjectPrx
{
    public void addCliente(ClientePrx cliente);

    public void addCliente(ClientePrx cliente, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_addCliente(ClientePrx cliente);

    public Ice.AsyncResult begin_addCliente(ClientePrx cliente, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_addCliente(ClientePrx cliente, Ice.Callback __cb);

    public Ice.AsyncResult begin_addCliente(ClientePrx cliente, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_addCliente(ClientePrx cliente, Callback_Moderador_addCliente __cb);

    public Ice.AsyncResult begin_addCliente(ClientePrx cliente, java.util.Map<String, String> __ctx, Callback_Moderador_addCliente __cb);

    public Ice.AsyncResult begin_addCliente(ClientePrx cliente, 
                                            IceInternal.Functional_VoidCallback __responseCb, 
                                            IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_addCliente(ClientePrx cliente, 
                                            IceInternal.Functional_VoidCallback __responseCb, 
                                            IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                            IceInternal.Functional_BoolCallback __sentCb);

    public Ice.AsyncResult begin_addCliente(ClientePrx cliente, 
                                            java.util.Map<String, String> __ctx, 
                                            IceInternal.Functional_VoidCallback __responseCb, 
                                            IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_addCliente(ClientePrx cliente, 
                                            java.util.Map<String, String> __ctx, 
                                            IceInternal.Functional_VoidCallback __responseCb, 
                                            IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                            IceInternal.Functional_BoolCallback __sentCb);

    public void end_addCliente(Ice.AsyncResult __result);

    public void removeCliente(ClientePrx cliente);

    public void removeCliente(ClientePrx cliente, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_removeCliente(ClientePrx cliente);

    public Ice.AsyncResult begin_removeCliente(ClientePrx cliente, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_removeCliente(ClientePrx cliente, Ice.Callback __cb);

    public Ice.AsyncResult begin_removeCliente(ClientePrx cliente, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_removeCliente(ClientePrx cliente, Callback_Moderador_removeCliente __cb);

    public Ice.AsyncResult begin_removeCliente(ClientePrx cliente, java.util.Map<String, String> __ctx, Callback_Moderador_removeCliente __cb);

    public Ice.AsyncResult begin_removeCliente(ClientePrx cliente, 
                                               IceInternal.Functional_VoidCallback __responseCb, 
                                               IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_removeCliente(ClientePrx cliente, 
                                               IceInternal.Functional_VoidCallback __responseCb, 
                                               IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                               IceInternal.Functional_BoolCallback __sentCb);

    public Ice.AsyncResult begin_removeCliente(ClientePrx cliente, 
                                               java.util.Map<String, String> __ctx, 
                                               IceInternal.Functional_VoidCallback __responseCb, 
                                               IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_removeCliente(ClientePrx cliente, 
                                               java.util.Map<String, String> __ctx, 
                                               IceInternal.Functional_VoidCallback __responseCb, 
                                               IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                               IceInternal.Functional_BoolCallback __sentCb);

    public void end_removeCliente(Ice.AsyncResult __result);

    public void addOficinista(OficinistaPrx oficinista);

    public void addOficinista(OficinistaPrx oficinista, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_addOficinista(OficinistaPrx oficinista);

    public Ice.AsyncResult begin_addOficinista(OficinistaPrx oficinista, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_addOficinista(OficinistaPrx oficinista, Ice.Callback __cb);

    public Ice.AsyncResult begin_addOficinista(OficinistaPrx oficinista, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_addOficinista(OficinistaPrx oficinista, Callback_Moderador_addOficinista __cb);

    public Ice.AsyncResult begin_addOficinista(OficinistaPrx oficinista, java.util.Map<String, String> __ctx, Callback_Moderador_addOficinista __cb);

    public Ice.AsyncResult begin_addOficinista(OficinistaPrx oficinista, 
                                               IceInternal.Functional_VoidCallback __responseCb, 
                                               IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_addOficinista(OficinistaPrx oficinista, 
                                               IceInternal.Functional_VoidCallback __responseCb, 
                                               IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                               IceInternal.Functional_BoolCallback __sentCb);

    public Ice.AsyncResult begin_addOficinista(OficinistaPrx oficinista, 
                                               java.util.Map<String, String> __ctx, 
                                               IceInternal.Functional_VoidCallback __responseCb, 
                                               IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_addOficinista(OficinistaPrx oficinista, 
                                               java.util.Map<String, String> __ctx, 
                                               IceInternal.Functional_VoidCallback __responseCb, 
                                               IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                               IceInternal.Functional_BoolCallback __sentCb);

    public void end_addOficinista(Ice.AsyncResult __result);

    public void removeOficinista(OficinistaPrx oficinista);

    public void removeOficinista(OficinistaPrx oficinista, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_removeOficinista(OficinistaPrx oficinista);

    public Ice.AsyncResult begin_removeOficinista(OficinistaPrx oficinista, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_removeOficinista(OficinistaPrx oficinista, Ice.Callback __cb);

    public Ice.AsyncResult begin_removeOficinista(OficinistaPrx oficinista, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_removeOficinista(OficinistaPrx oficinista, Callback_Moderador_removeOficinista __cb);

    public Ice.AsyncResult begin_removeOficinista(OficinistaPrx oficinista, java.util.Map<String, String> __ctx, Callback_Moderador_removeOficinista __cb);

    public Ice.AsyncResult begin_removeOficinista(OficinistaPrx oficinista, 
                                                  IceInternal.Functional_VoidCallback __responseCb, 
                                                  IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_removeOficinista(OficinistaPrx oficinista, 
                                                  IceInternal.Functional_VoidCallback __responseCb, 
                                                  IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                                  IceInternal.Functional_BoolCallback __sentCb);

    public Ice.AsyncResult begin_removeOficinista(OficinistaPrx oficinista, 
                                                  java.util.Map<String, String> __ctx, 
                                                  IceInternal.Functional_VoidCallback __responseCb, 
                                                  IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_removeOficinista(OficinistaPrx oficinista, 
                                                  java.util.Map<String, String> __ctx, 
                                                  IceInternal.Functional_VoidCallback __responseCb, 
                                                  IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                                  IceInternal.Functional_BoolCallback __sentCb);

    public void end_removeOficinista(Ice.AsyncResult __result);

    public void responderCliente(OficinistaPrx oficinista, String mensaje);

    public void responderCliente(OficinistaPrx oficinista, String mensaje, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_responderCliente(OficinistaPrx oficinista, String mensaje);

    public Ice.AsyncResult begin_responderCliente(OficinistaPrx oficinista, String mensaje, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_responderCliente(OficinistaPrx oficinista, String mensaje, Ice.Callback __cb);

    public Ice.AsyncResult begin_responderCliente(OficinistaPrx oficinista, String mensaje, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_responderCliente(OficinistaPrx oficinista, String mensaje, Callback_Moderador_responderCliente __cb);

    public Ice.AsyncResult begin_responderCliente(OficinistaPrx oficinista, String mensaje, java.util.Map<String, String> __ctx, Callback_Moderador_responderCliente __cb);

    public Ice.AsyncResult begin_responderCliente(OficinistaPrx oficinista, 
                                                  String mensaje, 
                                                  IceInternal.Functional_VoidCallback __responseCb, 
                                                  IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_responderCliente(OficinistaPrx oficinista, 
                                                  String mensaje, 
                                                  IceInternal.Functional_VoidCallback __responseCb, 
                                                  IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                                  IceInternal.Functional_BoolCallback __sentCb);

    public Ice.AsyncResult begin_responderCliente(OficinistaPrx oficinista, 
                                                  String mensaje, 
                                                  java.util.Map<String, String> __ctx, 
                                                  IceInternal.Functional_VoidCallback __responseCb, 
                                                  IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_responderCliente(OficinistaPrx oficinista, 
                                                  String mensaje, 
                                                  java.util.Map<String, String> __ctx, 
                                                  IceInternal.Functional_VoidCallback __responseCb, 
                                                  IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                                  IceInternal.Functional_BoolCallback __sentCb);

    public void end_responderCliente(Ice.AsyncResult __result);

    public void responderOficinista(ClientePrx cliente, String mensaje);

    public void responderOficinista(ClientePrx cliente, String mensaje, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_responderOficinista(ClientePrx cliente, String mensaje);

    public Ice.AsyncResult begin_responderOficinista(ClientePrx cliente, String mensaje, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_responderOficinista(ClientePrx cliente, String mensaje, Ice.Callback __cb);

    public Ice.AsyncResult begin_responderOficinista(ClientePrx cliente, String mensaje, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_responderOficinista(ClientePrx cliente, String mensaje, Callback_Moderador_responderOficinista __cb);

    public Ice.AsyncResult begin_responderOficinista(ClientePrx cliente, String mensaje, java.util.Map<String, String> __ctx, Callback_Moderador_responderOficinista __cb);

    public Ice.AsyncResult begin_responderOficinista(ClientePrx cliente, 
                                                     String mensaje, 
                                                     IceInternal.Functional_VoidCallback __responseCb, 
                                                     IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_responderOficinista(ClientePrx cliente, 
                                                     String mensaje, 
                                                     IceInternal.Functional_VoidCallback __responseCb, 
                                                     IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                                     IceInternal.Functional_BoolCallback __sentCb);

    public Ice.AsyncResult begin_responderOficinista(ClientePrx cliente, 
                                                     String mensaje, 
                                                     java.util.Map<String, String> __ctx, 
                                                     IceInternal.Functional_VoidCallback __responseCb, 
                                                     IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_responderOficinista(ClientePrx cliente, 
                                                     String mensaje, 
                                                     java.util.Map<String, String> __ctx, 
                                                     IceInternal.Functional_VoidCallback __responseCb, 
                                                     IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                                     IceInternal.Functional_BoolCallback __sentCb);

    public void end_responderOficinista(Ice.AsyncResult __result);
}
